packages:
  - apps/*
  - packages/*

catalog:
  "@cloudflare/workers-types": ^4.20251213.0
  "@libsql/client": 0.15.15
  "@livestore/adapter-web": 0.4.0-dev.22
  "@livestore/devtools-vite": 0.4.0-dev.22
  "@livestore/livestore": 0.4.0-dev.22
  "@livestore/peer-deps": 0.4.0-dev.22
  "@livestore/react": 0.4.0-dev.22
  "@livestore/sync-cf": 0.4.0-dev.22
  "@livestore/wa-sqlite": 0.4.0-dev.22
  "@orpc/client": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/server": ^1.12.2
  "@orpc/zod": ^1.12.2
  alchemy: 0.82.2
  better-auth: ^1.4.9
  dotenv: ^17.2.2
  drizzle-orm: ^0.45.1
  hono: 4.11.3
  libsql: 0.5.22
  nanoid: ^5.1.6
  typescript: ^5
  y-durableobjects: ^1.0.5
  zod: ^4.1.13
