/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TodosRouteImport } from "./routes/todos";
import { Route as NovelRouteImport } from "./routes/novel";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as NovelNovelIdRouteImport } from "./routes/novel.$novelId";
import { Route as NovelNovelIdIndexRouteImport } from "./routes/novel.$novelId.index";
import { Route as NovelNovelIdVolumeIdRouteImport } from "./routes/novel.$novelId.$volumeId";
import { Route as NovelNovelIdVolumeIdIndexRouteImport } from "./routes/novel.$novelId.$volumeId.index";
import { Route as NovelNovelIdVolumeIdChapterIdRouteImport } from "./routes/novel.$novelId.$volumeId.$chapterId";

const TodosRoute = TodosRouteImport.update({
  id: "/todos",
  path: "/todos",
  getParentRoute: () => rootRouteImport,
} as any);
const NovelRoute = NovelRouteImport.update({
  id: "/novel",
  path: "/novel",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const NovelNovelIdRoute = NovelNovelIdRouteImport.update({
  id: "/$novelId",
  path: "/$novelId",
  getParentRoute: () => NovelRoute,
} as any);
const NovelNovelIdIndexRoute = NovelNovelIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => NovelNovelIdRoute,
} as any);
const NovelNovelIdVolumeIdRoute = NovelNovelIdVolumeIdRouteImport.update({
  id: "/$volumeId",
  path: "/$volumeId",
  getParentRoute: () => NovelNovelIdRoute,
} as any);
const NovelNovelIdVolumeIdIndexRoute = NovelNovelIdVolumeIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => NovelNovelIdVolumeIdRoute,
} as any);
const NovelNovelIdVolumeIdChapterIdRoute = NovelNovelIdVolumeIdChapterIdRouteImport.update({
  id: "/$chapterId",
  path: "/$chapterId",
  getParentRoute: () => NovelNovelIdVolumeIdRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/novel": typeof NovelRouteWithChildren;
  "/todos": typeof TodosRoute;
  "/novel/$novelId": typeof NovelNovelIdRouteWithChildren;
  "/novel/$novelId/$volumeId": typeof NovelNovelIdVolumeIdRouteWithChildren;
  "/novel/$novelId/": typeof NovelNovelIdIndexRoute;
  "/novel/$novelId/$volumeId/$chapterId": typeof NovelNovelIdVolumeIdChapterIdRoute;
  "/novel/$novelId/$volumeId/": typeof NovelNovelIdVolumeIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/novel": typeof NovelRouteWithChildren;
  "/todos": typeof TodosRoute;
  "/novel/$novelId": typeof NovelNovelIdIndexRoute;
  "/novel/$novelId/$volumeId/$chapterId": typeof NovelNovelIdVolumeIdChapterIdRoute;
  "/novel/$novelId/$volumeId": typeof NovelNovelIdVolumeIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/novel": typeof NovelRouteWithChildren;
  "/todos": typeof TodosRoute;
  "/novel/$novelId": typeof NovelNovelIdRouteWithChildren;
  "/novel/$novelId/$volumeId": typeof NovelNovelIdVolumeIdRouteWithChildren;
  "/novel/$novelId/": typeof NovelNovelIdIndexRoute;
  "/novel/$novelId/$volumeId/$chapterId": typeof NovelNovelIdVolumeIdChapterIdRoute;
  "/novel/$novelId/$volumeId/": typeof NovelNovelIdVolumeIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/login"
    | "/novel"
    | "/todos"
    | "/novel/$novelId"
    | "/novel/$novelId/$volumeId"
    | "/novel/$novelId/"
    | "/novel/$novelId/$volumeId/$chapterId"
    | "/novel/$novelId/$volumeId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/login"
    | "/novel"
    | "/todos"
    | "/novel/$novelId"
    | "/novel/$novelId/$volumeId/$chapterId"
    | "/novel/$novelId/$volumeId";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/login"
    | "/novel"
    | "/todos"
    | "/novel/$novelId"
    | "/novel/$novelId/$volumeId"
    | "/novel/$novelId/"
    | "/novel/$novelId/$volumeId/$chapterId"
    | "/novel/$novelId/$volumeId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  NovelRoute: typeof NovelRouteWithChildren;
  TodosRoute: typeof TodosRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/todos": {
      id: "/todos";
      path: "/todos";
      fullPath: "/todos";
      preLoaderRoute: typeof TodosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/novel": {
      id: "/novel";
      path: "/novel";
      fullPath: "/novel";
      preLoaderRoute: typeof NovelRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/novel/$novelId": {
      id: "/novel/$novelId";
      path: "/$novelId";
      fullPath: "/novel/$novelId";
      preLoaderRoute: typeof NovelNovelIdRouteImport;
      parentRoute: typeof NovelRoute;
    };
    "/novel/$novelId/": {
      id: "/novel/$novelId/";
      path: "/";
      fullPath: "/novel/$novelId/";
      preLoaderRoute: typeof NovelNovelIdIndexRouteImport;
      parentRoute: typeof NovelNovelIdRoute;
    };
    "/novel/$novelId/$volumeId": {
      id: "/novel/$novelId/$volumeId";
      path: "/$volumeId";
      fullPath: "/novel/$novelId/$volumeId";
      preLoaderRoute: typeof NovelNovelIdVolumeIdRouteImport;
      parentRoute: typeof NovelNovelIdRoute;
    };
    "/novel/$novelId/$volumeId/": {
      id: "/novel/$novelId/$volumeId/";
      path: "/";
      fullPath: "/novel/$novelId/$volumeId/";
      preLoaderRoute: typeof NovelNovelIdVolumeIdIndexRouteImport;
      parentRoute: typeof NovelNovelIdVolumeIdRoute;
    };
    "/novel/$novelId/$volumeId/$chapterId": {
      id: "/novel/$novelId/$volumeId/$chapterId";
      path: "/$chapterId";
      fullPath: "/novel/$novelId/$volumeId/$chapterId";
      preLoaderRoute: typeof NovelNovelIdVolumeIdChapterIdRouteImport;
      parentRoute: typeof NovelNovelIdVolumeIdRoute;
    };
  }
}

interface NovelNovelIdVolumeIdRouteChildren {
  NovelNovelIdVolumeIdChapterIdRoute: typeof NovelNovelIdVolumeIdChapterIdRoute;
  NovelNovelIdVolumeIdIndexRoute: typeof NovelNovelIdVolumeIdIndexRoute;
}

const NovelNovelIdVolumeIdRouteChildren: NovelNovelIdVolumeIdRouteChildren = {
  NovelNovelIdVolumeIdChapterIdRoute: NovelNovelIdVolumeIdChapterIdRoute,
  NovelNovelIdVolumeIdIndexRoute: NovelNovelIdVolumeIdIndexRoute,
};

const NovelNovelIdVolumeIdRouteWithChildren = NovelNovelIdVolumeIdRoute._addFileChildren(
  NovelNovelIdVolumeIdRouteChildren,
);

interface NovelNovelIdRouteChildren {
  NovelNovelIdVolumeIdRoute: typeof NovelNovelIdVolumeIdRouteWithChildren;
  NovelNovelIdIndexRoute: typeof NovelNovelIdIndexRoute;
}

const NovelNovelIdRouteChildren: NovelNovelIdRouteChildren = {
  NovelNovelIdVolumeIdRoute: NovelNovelIdVolumeIdRouteWithChildren,
  NovelNovelIdIndexRoute: NovelNovelIdIndexRoute,
};

const NovelNovelIdRouteWithChildren = NovelNovelIdRoute._addFileChildren(NovelNovelIdRouteChildren);

interface NovelRouteChildren {
  NovelNovelIdRoute: typeof NovelNovelIdRouteWithChildren;
}

const NovelRouteChildren: NovelRouteChildren = {
  NovelNovelIdRoute: NovelNovelIdRouteWithChildren,
};

const NovelRouteWithChildren = NovelRoute._addFileChildren(NovelRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NovelRoute: NovelRouteWithChildren,
  TodosRoute: TodosRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
